kind: pipeline
name: default
type: kubernetes

services:
- name: selenium
  image: selenium/standalone-chrome:4.0.0-rc-1-20210902
  detach: true
  environment: 
    SE_OPTS: "--host 127.0.0.1 --log-level FINE"

steps:
- name: tests
  image: crystallang/crystal:1.1.1
  network_mode: host
  environment: 
    CI: true
  commands: 
    - crystal spec
