kind: pipeline
name: default
type: kubernetes
services:
- name: selenium
  image: selenium/standalone-chrome:4.0.0-rc-2-20210930
  volumes:
    - name: droneshm
      path: /dev/shm
  environment: 
    SE_OPTS: "--host 127.0.0.1 --log-level FINEST"
    SE_NODE_MAX_SESSIONS: 10
    START_XVFB: false

steps:
- name: tests
  image: crystallang/crystal:1.1.1
  environment: 
    CI: true
  commands: 
    - crystal spec
volumes:
  - name: droneshm
    temp: {}
