kind: pipeline
name: default
type: kubernetes

services:
- name: selenium
  image: selenium/standalone-chrome:4.0.0-rc-1-20210902
  network_mode: host
  environment: 
    SE_OPTS: "--host 0.0.0.0"
  detach: true

steps:
- name: server
  image: crystallang/crystal:1.1.1
  network_mode: host
  environment: 
    CI: true
  commands: 
    - crystal spec
