image: skinnyjames/crystal-chromedriver

before_script:
  - shards install

cache:
  paths:
  - lib/

test:
  script:
    - crystal spec
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

pages:
  stage: deploy
  script:
  - crystal docs -o public src/webdriver.cr
  artifacts:
    paths:
    - public
  only:
  - wip
