image: jekyll/jekyll

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - jekyll build -d docs
  artifacts:
    paths:
      - docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "wip"'
