image: ruby:2.7

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d docs
  artifacts:
    paths:
      - docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "wip"'
